ci: Adding PR template and release notes generator (#1221)
## Description

Describe the changes or additions included in this PR.

## Test plan
Error:
https://github.com/MystenLabs/walrus/actions/runs/12037061150/job/33559677863?pr=1221
```
WALRUS_REPO_TOKEN=*** python ./scripts/release_notes.py check 1221
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/[3](https://github.com/MystenLabs/walrus/actions/runs/12037061150/job/33559677863?pr=1221#step:4:3).10.10/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.10.10/x6[4](https://github.com/MystenLabs/walrus/actions/runs/12037061150/job/33559677863?pr=1221#step:4:4)/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.10/x[6](https://github.com/MystenLabs/walrus/actions/runs/12037061150/job/33559677863?pr=1221#step:4:6)4
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.10/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.10/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.10/x64/lib
DEBUG: curl_command=['curl', '-s', '-H', 'Accept: application/vnd.github.groot-preview+json', '-H', 'Authorization: ***', 'https://api.github.com/repos/MystenLabs/walrus/pulls/1221'], type=<class 'list'>
Found issues with release notes in PR 1221:
 - 'Storage node' is checked but has no release note.
Error: Process completed with exit code 1.
```
No Error: 

https://github.com/MystenLabs/walrus/actions/runs/12037082029/job/33559744785?pr=1221

---

## Release notes

Check each box that your changes affect. If none of the boxes relate to
your changes, release notes aren't required.
For each box you select, include information after the relevant heading
that describes the impact of your changes that
a user might notice and any actions they must take to implement updates.
(Add release notes after the colon for each item)

- [ ] Storage node:
- [ ] Aggregator:
- [ ] Publisher:
- [ ] CLI: